# Generated by Django 3.2.12 on 2022-05-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KidsGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='Название')),
                ('message', models.TextField(null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Игры',
            },
        ),
    ]
